### ISSUE TITLE
error :  "timed out" when calling makeInvoice

### ISSUE THREAD

**Issue by ninabreznik** [supertestnet/nwcjs#1]
Hi,

I am trying to use your library to create an invoice (and later I would also like to use it to pay the invoice), but am getting `error: "timed out"` for some reason.

Here's my code https://github.com/ninabreznik/simple-payInvoice/tree/main/src and your modules (a tiny bit refactored so I can require them) are under src/node_modules.

Here's also a super simple UI https://ninabreznik.github.io/simple-payInvoice/

If you know wha could be the problem, I would be super grateful if you'd let me know. I tried with setting seconds_of_delay_tolerable to 5s, but it still doesn't do the trick.

**Comment by supertestnet** [comment]
Hi Nina,

I cloned your repo and ran it with `npm run start` but as soon as I clicked "Create invoice" I got an error from the nobleSecp256k1 library:

`Uncaught (in promise) TypeError: crypto.web.subtle is undefined`

I think it is because the window.crypto object lacks the `subtle` cryptography methods when not served on an https website. Consequently, the page can't run sha256, and I run into an error before I can properly test your app.

That said, I suspect there are a few problems:

- your node_modules directory only contains two js files, noble-secp256k1.js and nwcjs. It should also have browserify-cipher and bech32. 
- my nwcjs library *also* relies on websockets, which are built into all modern browsers but are not part of nodejs by default. I usually run this in my nodejs projects to get websockets:

> npm install ws
> var WebSocket = require( 'ws' ).WebSocket;

Let me know if those pointers help. Thanks for the issue!

**Comment by ninabreznik** [comment]
Thanks, for your answer :)

I forgot to mention I run the project locally on `http://localhost:9966/` and avoid the `crypto.web.subtle` problem this way.

I will try the two points you mention and hopefully this will do.

Need to mention again how happy I am for your code as it is super readable and minimalist so I can actually understand what is going on most of the time. Really appreciate it.

Will let you know once I make it work or if I continue getting stuck. Thanks once again!!

**Comment by ninabreznik** [comment]
Perfect, it works now. The problem was I had all the modules (some in my src/node_modules folder and some in my html as bundles, but I duplicated noble-secp256k1 and had it in both, so I removed it from the html).

This now made the code run well and I got a reponse from the relay (type: make_invoice), but sadly still no invoice, but this time `Method not supported`. I assume this means my wallet doesn't support make_invoice method?
![Screenshot_2024-09-14_20-46-51](https://github.com/user-attachments/assets/d762ef31-2484-4403-b512-90660f8c09dd)

**Comment by supertestnet** [comment]
> I assume this means my wallet doesn't support make_invoice method?

That is probably true. Several popular wallets don't support that method, e.g. minibits and cashu.me don't support it. You should be able to find out what methods your backend supports by running `getInfo()` -- though there's a chance they don't support *that* method either, lol

https://github.com/supertestnet/nwcjs/tree/main?tab=readme-ov-file#get-info

**Comment by ninabreznik** [comment]
Thanks. Any wallets that support NWC (and most methods) you would recommend? I saw you are building one too :)

**Comment by ninabreznik** [comment]
This has been resolved for me. Thanks

**Comment by supertestnet** [comment]
> Thanks. Any wallets that support NWC (and most methods) you would recommend? I saw you are building one too :)

I apologize for not seeing this question sooner

The best NWC backends are probably [Alby Hub](https://albyhub.com/) and [coinos.io](https://coinos.io/)

I also made [bankify](https://supertestnet.github.io/bankify/) which turns any ecash mint into an NWC backend, but it's all done in client-side javascript which means it only works while the page is open

For more info about NWC backends I recommend asking in the NWC discord channel: https://discord.gg/5C4aSp7v

**Comment by ninabreznik** [comment]
Thanks a lot!
